What The Hike/Controllers/HikeController.cs
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using What_The_Hike.Models;

namespace What_The_Hike.Controllers
{
    public class HikeController : Controller
    {
        //private readonly HikeContext db;

        // GET: Hike
        [HttpGet]
        public JsonResult Index()
        {
            List<HikeGeneralView> hikes = new List<HikeGeneralView>();
            using (HikeContext db = new HikeContext())
            {
                var hikesDB = db.Hike.ToList();
                foreach (var item in hikesDB)
                {
                    Difficulty difficulty = db.Difficulty.Where(e => e.difficultyID == item.difficultyID).FirstOrDefault();
                    Facility facility = db.Facility.Where(e => e.facilityID == item.facilityID).FirstOrDefault();
                    Duration duration = db.Duration.Where(e => e.durationID == item.avgDuration).FirstOrDefault();
                    hikes.Add(new HikeGeneralView
                    {
                        hikeID = item.hikeID,
                        name = item.name,
                        map = item.map,
                        description = item.description,
                        coordinates = item.coordinates,
                        distance = item.distance,
                        enteranceFee = item.enteranceFee,
                        maxGroupSize = item.maxGroupSize,
                        difficulty = difficulty.description,
                        duration = duration.time,
                        facilityId = facility.facilityID,
                        facilityName = facility.name,
                    }
                    );
                }
            }
            this.HttpContext.Response.StatusCode = 200;

            if (hikes.Count > 0)
            {
                var Ret = new ReturnObject
                {
                    success = true,
                    message = "Hikes Retrieved",
                    data = Json(hikes.OrderBy(e => e.hikeID).ToList()).Data
                };
                return Json(Ret, JsonRequestBehavior.AllowGet);
            }
            else
            {
                var Ret = new ReturnObject
                {
                    success = false,
                    message = "No Hikes Available",
                    data = new { }
                };
                return Json(Ret, JsonRequestBehavior.AllowGet);
            }
        }

        // GET: Hike/getHike/{id}
        [HttpGet]
        public JsonResult GetHike(int id)
        {
            HikeDetailView hike = null;

            using (HikeContext db = new HikeContext())
            {
                Hike hikeDB = db.Hike.Where(e => e.hikeID == id).FirstOrDefault();
                if (hikeDB != null)
                {
                    Difficulty difficultyDB = db.Difficulty.Where(e => e.difficultyID == hikeDB.difficultyID).FirstOrDefault();
                    Facility facilityDB = db.Facility.Where(e => e.facilityID == hikeDB.facilityID).FirstOrDefault();
                    Duration durationDB = db.Duration.Where(e => e.durationID == hikeDB.avgDuration).FirstOrDefault();

                    FacilityView facility = new FacilityView
                    {
                        facilityID = facilityDB.facilityID,
                        name = facilityDB.name,
                        latitude = facilityDB.latitude,
                        longitude = facilityDB.longitude,
                        parking = facilityDB.parking,
                        pets = facilityDB.pets,
                        bookingRequired = facilityDB.bookingRequired,
                        HikesInFacility = getHikesByFacilityId(facilityDB.facilityID)
                    };

                    hike = new HikeDetailView
                    {
                        hikeID = hikeDB.hikeID,
                        name = hikeDB.name,
                        map = hikeDB.map,
                        description = hikeDB.description,
                        coordinates = hikeDB.coordinates,
                        distance = hikeDB.distance,
                        enteranceFee = hikeDB.enteranceFee,
                        maxGroupSize = hikeDB.maxGroupSize,
                        difficulty = difficultyDB.description,
                        duration = durationDB.time,
                        facility = facility,
                        pointsOfInterest = PointsOfInterest(hikeDB.hikeID)
                    };
                }
            }
            if (hike != null)
            {
                var Ret = new ReturnObject
                {
                    success = true,
                    message = "Hike Retrieved",
                    data = hike
                };
                return Json(Ret, JsonRequestBehavior.AllowGet);
            }
            else
            {
                var Ret = new ReturnObject
                {
                    success = false,
                    message = "No Hike with given ID",
                    data = new { }
                };
                return Json(Ret, JsonRequestBehavior.AllowGet);
            }
        }

        private List<PointOfInterestView> PointsOfInterest(int hikeID)
        {
            List<PointOfInterestView> poi = new List<PointOfInterestView>();
            using (HikeContext db = new HikeContext())
            {
                var poiIDs = db.HikeInterestLink.Where(e => e.hikeID == hikeID).Select(e => e.pointOfInterestID).ToList();
                var points = db.PointOfInterest.Where(e => poiIDs.Contains(e.pointOfInterestID)).ToList();
                foreach (var item in points)
                    if (poi.Where(e => e.poiID == item.pointOfInterestID).FirstOrDefault() == null)
                        poi.Add(new PointOfInterestView { poiID = item.pointOfInterestID, PointOfInterestDescription = item.description });
            }
            return poi;
        }

        public List<HikeSimpleView> getHikesByFacilityId(int facilityId)
        {
            List<HikeSimpleView> hikes = new List<HikeSimpleView>();
            using (HikeContext db = new HikeContext())
            {
                var hikesDB = db.Hike.Where(e => e.facilityID == facilityId).ToList();
                foreach (var item in hikesDB)
                {
                    hikes.Add(new HikeSimpleView { hikeID = item.hikeID, name = item.name });
                }
            }

            return hikes;
        }

        // GET: Hike/Weather/{id}
        [HttpGet]
        public ContentResult Weather(int id)
        {
            JObject Ret = new JObject();
            Hike hike = null;
            Facility facility = null;
            using (HikeContext db = new HikeContext())
            {
                hike = db.Hike.Where(e => e.hikeID == id).FirstOrDefault();
                if (hike != null)
                {
                    facility = db.Facility.Where(e => e.facilityID == hike.facilityID).FirstOrDefault();
                }
            }


            if (facility != null)
            {
                HttpClient client = new HttpClient();
                client.BaseAddress = new Uri("https://api.openweathermap.org/");
                var latitude = facility.latitude;
                var longitude = facility.longitude;
                var apiKey = "7db484b6881763be58be890766009069";
                string endpoint = $"data/2.5/onecall?lat={latitude}&lon={longitude}&units=metric&appid={apiKey}";

                HttpResponseMessage response = client.GetAsync(endpoint).Result;
                if (response.IsSuccessStatusCode)
                {
                    Ret.Add("success", true);
                    Ret.Add("message", "Weather retrieved");
                    Ret.Add("data", JObject.Parse(response.Content.ReadAsStringAsync().Result.Replace("\\", string.Empty)));
                }
                else
                {
                    Console.WriteLine("{0} ({1})", (int)response.StatusCode, response.ReasonPhrase);
                    Ret.Add("success", false);
                    Ret.Add("message", "Weather API call Failed");
                    Ret.Add("data", null);
                }
            }
            else
            {
                Ret.Add("success", false);
                Ret.Add("data", null);
                if (hike == null)
                {
                    Ret.Add("message", "No Hike with the given ID");
                }
                else
                {
                    Ret.Add("message", "No Facility with the given HikeID");
                }
            }

            return Content(JsonConvert.SerializeObject(Ret), "application/json");
        }

        //POST: Hike/logs
        [HttpPost]
        [Authorize]
        //[ValidateAntiForgeryToken]
        public ContentResult Create(HikeLog_UserHikeID hikeLog)
        {
            JObject Ret = new JObject();
            if (ModelState.IsValid )
            {
                //hikeLog.User;
                using (HikeContext db = new HikeContext())
                {

                    db.HikeLog.Add(new HikeLog() { hikeID = Int32.Parse(hikeLog.hikeID), userID = Int32.Parse(hikeLog.userID)
                    });
                    db.SaveChanges();
                    Ret.Add("success", true);
                    Ret.Add("message", "Created New Log.");
                    return Content(JsonConvert.SerializeObject(Ret), "application/json");
                }
            }
            Ret.Add("success", false);
            Ret.Add("message", "Errors In Model.");
            return Content(JsonConvert.SerializeObject(Ret), "application/json");
        }

        //Get: Hike/logs 

What The Hike/Controllers/HomeController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using What_The_Hike.Models;

namespace What_The_Hike.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
        [HttpGet]
        [Authorize]
        public ActionResult ViewHikeLog()
        {
            HikeLog_UserHikeID logs = new HikeLog_UserHikeID() { User = new List<User>(), Hike = new List<Hike>() };
            using (HikeContext db = new HikeContext())
            {
                logs.User.AddRange(
                   db.User.ToList());
                logs.Hike.AddRange(
                   db.Hike.ToList());
            }

            return View(logs);
        }
    }
}

What The Hike/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

What The Hike/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

What The Hike/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

@{ Layout = "~/Views/Shared/_Layout.cshtml"; }

<div class="jumbotron">
    <h1>What The Hike</h1>
    <p class="lead">
        Providing you with info about your favourite Hikes
    </p>
</div>

<div class="row">
    <div class="col-md-6">
        <h2>Our End Points</h2>
        <ul>
            <li>
                <a href="/Admin/Facility/1">
                    View Facility
                </a>
            </li>
            <li>
                <a href="/Admin/GetLocation/1">
                    Get Location
                </a>
            </li>
            <li>
                <a href="/Hike">
                    Get Hikes
                </a>
            </li>
            <li>
                <a href="/Hike/GetHike/1">
                    Get Specific Hike
                </a>
            </li>
            <li>
                <a href="/Hike/Weather/1">
                    Get Weather For Hike
                </a>
            </li>
            <li>
                <a href="/Hike/LeaderBoard">
                    Get Leader Board
                </a>
            </li>
            <li>
                <a href="/Home/ViewHikeLog">
                    Log New Hike
                </a>
            </li>
        </ul>
    </div>
    <div class="col-md-6">
        <h2>Team Members</h2>
        <ul>
            <li>Stuart Barclay</li>
            <li>Keamo Mfoloe</li>
            <li>Kiara Smith</li>
            <li>Duncan Vodden</li>
            <li>Thami Xabanisa</li>
        </ul>
    </div>
</div>

What The Hike/Views/Home/ViewHikeLog.cshtml
@model What_The_Hike.HikeLog_UserHikeID
@{ Layout = "~/Views/Shared/_Layout.cshtml"; }

@using (Html.BeginForm("Create", "Hike", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
<h2>Log a new hike.</h2>
                <hr />
                                @Html.AntiForgeryToken()
                                                @Html.ValidationSummary(false, "", new { @class = "text-danger" })
                                                                <div class="form-group">
                                                                    <label for="hikeID" class="col-md-2 control-label">Select A Hike Location</label>
                                                                    <div class="col-md-10">
                                                                        <select name="hikeID" id="hikeID" class="form-control">
                                                                            @{foreach (var item in Model.Hike)
                                                                                {
                                                                <option value="@item.hikeID">
                                                                    @item.name
                                                                </option> } }
                                                                        </select>
                                                                    </div>
                                                                </div>

                                                                                <div class="form-group">
                                                                                    <label for="userID" class="col-md-2 control-label">Select A User</label>
                                                                                    <div class="col-md-10">
                                                                                        <select name="userID" id="userID" class="form-control">

                                                                                            @{ foreach (var item in Model.User)
                                                                                                {
                                                                                <option value="@item.userID">
                                                                                    @item.name @item.surname
                                                                                </option> } }
                                                                                        </select>
                                                                                    </div>
                                                                                </div>
                                                                                                <button class="btn btn-primary" type="submit">Submit</button>}